Fix units
FG-TUM/OrbitPropagator pull request #2
Opened 2022-01-27 16:24 UTC by FG-TUM

# Description

- [x] fixed wrong unit for `Physics::P_GROUND`
- [x] add units to constants
- [x] fixed drag calculation (wrong units and missing `vNorm`)
- [x] adapted tests
- [ ] Test 1 month run with LADDS

2022-01-27 16:27 UTC, FG-TUM commented
I guess that also means we should change all example data's bc_inf from 2e-5 to 2e-3. That way we actually get a `c_D` of 2.5

2022-01-28 10:00 UTC, gomezzz commented
> I guess that also means we should change all example data's bc_inf from 2e-5 to 2e-3. That way we actually get a c_D of 2.5

Why 2.5 though? Aren't we aiming for 2.2?

2022-01-28 10:01 UTC, gomezzz requested changes
Could you run a quick  1month run or something just as a sanity check that we don't rapidly decay everything now? Because that certainly wouldn't be right either. (more indepth analysis of stability of orbital elements should probably follow later).

Also, tests are failing :)

2022-01-28 13:00 UTC, FG-TUM commented
> Why 2.5 though? Aren't we aiming for 2.2?

We - yes. But apparently this repo in it's example input not.

2022-01-28 13:03 UTC, FG-TUM commented on src/satellitePropagator/physics/Constants.h
>  inline constexpr double GM_EARTH = 3.986004407799724e+5;
so you want this to be renamed to `MU_EARTH`? And I guess accordingly for the other bodies?

2022-01-28 13:07 UTC, FG-TUM commented on src/satellitePropagator/physics/Constants.h
>   * - Acceleration::SolComponent
it actually isn't. fixed -> a743fd9

2022-01-28 13:17 UTC, gomezzz commented on src/satellitePropagator/physics/Constants.h
>  inline constexpr double GM_EARTH = 3.986004407799724e+5;
Meh, then let's keep it, greek letters don't make for great code anyways

2022-01-28 13:19 UTC, gomezzz approved these changes
Looks good, only thing as comment in earlier review:
> Could you run a quick 1month run or something just as a sanity check that we don't rapidly decay everything now? Because that certainly wouldn't be right either. (more indepth analysis of stability of orbital elements should probably follow later).

Maybe we create an issue for this in the LADDS repo?

2022-01-28 14:25 UTC, FG-TUM commented on src/satellitePropagator/physics/Constants.h
>  inline constexpr double GM_EARTH = 3.986004407799724e+5;
> Maybe we create an issue for this in the LADDS repo?

No I want to fix test this before we merge this.

2022-01-28 14:25 UTC, FG-TUM commented
> Maybe we create an issue for this in the LADDS repo?

No I want to fix test this before we merge this.

2022-02-11 08:30 UTC, gomezzz approved these changes

2022-02-11 10:15 UTC, merged